import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Geist, Geist_Mono } from "next/font/google";
import NavigationBar from "@/components/NavigationBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Share work",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <main >
                <NavigationBar />
                <AntdRegistry>{children}</AntdRegistry>
            </main>
            {/* <html lang="en">
                <head />
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <NavigationBar />
                    <AntdRegistry>{children}</AntdRegistry>
                </body>
            </html> */}
        </>
    );
}
