import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
// import { Geist, Geist_Mono } from "next/font/google";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Share work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    //     <AntdRegistry>
    //       <NavigationBar/>
    //       {children}
    //     </AntdRegistry>
    //   </body>
    // </html>
    <div>
      <AntdRegistry>
        {children}
      </AntdRegistry>
    </div>
  );
}
