export const industries  = [
    { value: "it", label: "Công nghệ thông tin" },
    { value: "marketing", label: "Marketing" },
    { value: "finance", label: "Tài chính / Ngân hàng" },
    { value: "education", label: "Giáo dục / Đào tạo" },
    { value: "design", label: "Thiết kế / Sáng tạo" },
    { value: "sales", label: "Bán hàng / Kinh doanh" },
    { value: "customer_service", label: "Chăm sóc khách hàng" },
    { value: "engineering", label: "Kỹ thuật" },
    { value: "human_resources", label: "Nhân sự" },
    { value: "legal", label: "Pháp lý / Luật" },
    { value: "logistics", label: "Vận chuyển / Logistics" },
    { value: "media", label: "Truyền thông / Báo chí" },
    { value: "medical", label: "Y tế / Sức khỏe" },
    { value: "construction", label: "Xây dựng" },
    { value: "hospitality", label: "Nhà hàng / Khách sạn" },
    { value: "real_estate", label: "Bất động sản" },
    { value: "manufacturing", label: "Sản xuất / Chế biến" },
    { value: "agriculture", label: "Nông nghiệp / Thực phẩm" },
    { value: "environment", label: "Môi trường" },
    { value: "science", label: "Nghiên cứu / Khoa học" },
  ];