import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import RecruiterBar from "@/components/RecruiterBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Recruiter Home",
    description: "Generated by create next app",
};

export default function RecruiterLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {/* Thanh bar cố định */}
            <RecruiterBar />

            {/* Nội dung có thể cuộn */}
            <main
                style={{// Đẩy xuống để không bị đè lên bởi RecruiterBar
                    height: 'calc(100vh - 60px)', // Giới hạn chiều cao để có thể cuộn
                    overflowY: 'auto', // Cho phép cuộn theo chiều dọc
                }}
            >
                {children}
            </main>
        </>
    );
}
