// import type { Metadata } from "next";
// import { AntdRegistry } from '@ant-design/nextjs-registry';
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import NavigationBar from "@/components/NavigationBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Share work",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <AntdRegistry>
//           <NavigationBar />
//           {children}
//         </AntdRegistry>
//       </body>
//     </html>
//   );
// }

"use client"; // Phải có để sử dụng usePathname()
import { usePathname } from "next/navigation";
// import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Share work",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Lấy đường dẫn hiện tại

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AntdRegistry>
          {/* Chỉ hiển thị NavigationBar nếu không phải trang Login */}
          {pathname !== "/login" && <NavigationBar />}
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
