name: CI for Next.js

on:
  push:
    branches:
      - "*" # Trigger the workflow on all branches
  pull_request:
    branches:
      - "*" # Trigger the workflow on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Lint
      - name: Run ESLint
        run: npm run lint

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Run Tests (optional, nếu bạn chưa có test thì bỏ qua bước này)
      # - name: Run tests
      #   run: npm test
